use anyhow::Result;
use temporalio_client::{
    Client, ClientOptions, Connection, ConnectionOptions,
    WorkflowStartOptions, WorkflowSignalOptions, WorkflowQueryOptions,
    WorkflowTerminateOptions,
};
use temporalio_client::errors::WorkflowStartError;
use temporalio_sdk::workflows::WorkflowImplementation;

use crate::config::{Config, AgentConfig};
use crate::temporal::workflow::{
    AgentWorkflow, AgentWorkflowInput, IncomingMessage, AgentStatus, HistoryRecord, TASK_QUEUE,
};

/// The `Run` marker type generated by `#[workflow_methods]` for `AgentWorkflow`.
/// Signals/queries associate their `Workflow` with this type, not `AgentWorkflow` directly.
type AgentWorkflowRun = <AgentWorkflow as WorkflowImplementation>::Run;

pub struct TemporalDispatcher {
    client: Client,
    task_queue: String,
}

impl TemporalDispatcher {
    pub async fn new(config: &Config) -> Result<Self> {
        let temporal_cfg = config.temporal.as_ref()
            .ok_or_else(|| anyhow::anyhow!("[temporal] config required"))?;

        let target: url::Url = temporal_cfg.endpoint.parse()
            .map_err(|e: url::ParseError| anyhow::anyhow!("invalid temporal endpoint: {e}"))?;

        let connection = Connection::connect(
            ConnectionOptions::new(target)
                .identity("claude-chat-dispatcher".to_string())
                .build(),
        ).await?;

        let client = Client::new(
            connection,
            ClientOptions::new(&temporal_cfg.namespace).build(),
        )?;

        Ok(Self {
            client,
            task_queue: temporal_cfg.task_queue.clone(),
        })
    }

    /// Build AgentWorkflowInput from agent config and global config.
    pub fn build_workflow_input(
        agent_name: &str,
        agent_config: &AgentConfig,
        config: &Config,
    ) -> AgentWorkflowInput {
        AgentWorkflowInput {
            agent_name: agent_name.to_string(),
            session_id: agent_name.to_string(),
            room_id: agent_config.room_id.clone(),
            work_dir: agent_config.work_dir.clone(),
            store_dir: agent_config.store_dir.clone(),
            timeout_secs: agent_config.timeout(),
            claude_bin: std::env::var("CLAUDE_PATH").unwrap_or_else(|_| "claude".to_string()),
            claude_home: config.claude_home.clone(),
            vault_root: config.vault.as_ref().map(|v| v.root.clone()),
        }
    }

    /// Start the agent workflow if not already running. Idempotent.
    pub async fn ensure_running(
        &self,
        agent_name: &str,
        input: AgentWorkflowInput,
    ) -> Result<()> {
        let result = self.client.start_workflow(
            AgentWorkflow::run,
            input,
            WorkflowStartOptions::new(&self.task_queue, agent_name).build(),
        ).await;

        match result {
            Ok(_) => {
                tracing::info!(agent = %agent_name, "workflow started");
                metrics::counter!("claude_chat_temporal_workflow_started_total",
                    "agent" => agent_name.to_string()).increment(1);
            }
            Err(WorkflowStartError::AlreadyStarted { .. }) => {
                tracing::debug!(agent = %agent_name, "workflow already running");
            }
            Err(e) => return Err(e.into()),
        }
        Ok(())
    }

    /// Send a message signal to an agent's workflow.
    pub async fn send_message(
        &self,
        agent_name: &str,
        msg: IncomingMessage,
    ) -> Result<()> {
        let handle = self.client.get_workflow_handle::<AgentWorkflowRun>(agent_name);
        handle.signal(AgentWorkflow::incoming_message, msg, WorkflowSignalOptions::default()).await?;
        metrics::counter!("claude_chat_temporal_signals_sent_total",
            "agent" => agent_name.to_string(),
            "signal" => "incoming_message").increment(1);
        Ok(())
    }

    /// Send cancel signal to an agent's workflow.
    pub async fn cancel_agent(&self, agent_name: &str) -> Result<()> {
        let handle = self.client.get_workflow_handle::<AgentWorkflowRun>(agent_name);
        handle.signal(AgentWorkflow::cancel, (), WorkflowSignalOptions::default()).await?;
        metrics::counter!("claude_chat_temporal_signals_sent_total",
            "agent" => agent_name.to_string(),
            "signal" => "cancel").increment(1);
        Ok(())
    }

    /// Send reset signal to an agent's workflow.
    pub async fn reset_agent(&self, agent_name: &str) -> Result<()> {
        let handle = self.client.get_workflow_handle::<AgentWorkflowRun>(agent_name);
        handle.signal(AgentWorkflow::reset, (), WorkflowSignalOptions::default()).await?;
        metrics::counter!("claude_chat_temporal_signals_sent_total",
            "agent" => agent_name.to_string(),
            "signal" => "reset").increment(1);
        Ok(())
    }

    /// Query workflow status (synchronous read).
    pub async fn query_status(&self, agent_name: &str) -> Result<AgentStatus> {
        let handle = self.client.get_workflow_handle::<AgentWorkflowRun>(agent_name);
        Ok(handle.query(AgentWorkflow::status, (), WorkflowQueryOptions::default()).await?)
    }

    /// Query recent history (synchronous read).
    pub async fn query_history(&self, agent_name: &str, limit: u32) -> Result<Vec<HistoryRecord>> {
        let handle = self.client.get_workflow_handle::<AgentWorkflowRun>(agent_name);
        Ok(handle.query(AgentWorkflow::history, limit, WorkflowQueryOptions::default()).await?)
    }

    /// Terminate and restart a workflow (hard reset).
    pub async fn restart_workflow(
        &self,
        agent_name: &str,
        input: AgentWorkflowInput,
    ) -> Result<()> {
        let handle = self.client.get_workflow_handle::<AgentWorkflowRun>(agent_name);
        let _ = handle.terminate(
            WorkflowTerminateOptions::builder().reason("user reset").build()
        ).await;
        self.ensure_running(agent_name, input).await
    }
}
